{% macro tagging_setup() %}
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS TAGS;
CREATE SCHEMA IF NOT EXISTS TAGS.TAGS
    WITH COMMENT = 'Central database for tag management';

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TAG_ADMIN;
GRANT ROLE TAG_ADMIN TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE TAGS TO ROLE TAG_ADMIN;
GRANT USAGE ON SCHEMA TAGS.TAGS TO ROLE TAG_ADMIN;
GRANT CREATE TAG ON SCHEMA TAGS.TAGS TO ROLE TAG_ADMIN;

USE ROLE ACCOUNTADMIN;
GRANT APPLY TAG ON ACCOUNT TO ROLE TAG_ADMIN;
{% endmacro %}